### ISSUE TITLE
Source code for Generative PET

### ISSUE THREAD

**Issue by alisafaya** [timoschick/pet#28]
First of all, thanks for the huge effort.

I read your paper on Generative PET on ArXiv, you have mentioned that the source code is available on this repo, but it seems like you have not pushed it yet. I wonder if you are going to release the source code for Generative PET anytime soon.

**Comment by timoschick** [comment]
Hi @alisafaya, thanks for your interest in our work :)
We have made some quite substantial changes to our generative approach since the paper on Generative PET appeared on arXiv. However, we cannot make the most recent version publicly available due to an ongoing anonymity period. We'll release the source code along with the paper's most recent version as soon as it is no longer under review.

**Comment by alisafaya** [comment]
Thank you for your reply. 

I will be looking forward to read the published version of it!

I guess I should close this issue then. 

Thanks again!
