### ISSUE TITLE
What is the role of a verbalizer in text generation?

### ISSUE THREAD

**Issue by BleepLogger** [timoschick/pet#43]
The paper said GenPET wouldn't have a verbalizer. I know you said that the code in that feature branch had some stuff that wasn't talked about in the arxiv preprint. Is this one of them?

**Comment by timoschick** [comment]
Indeed GenPET does not need a verbalizer - you can still find verbalizers in the code because the feature branch also supports regular PET (which does require verbalizers). However, verbalizers are not used for text generation which is why [``GenerativePVP``](https://github.com/timoschick/pet/blob/60cec60272bdb6c3520de4cc4f3e33408eb018f9/pet/pvp.py#L260) has a default verbalizer function that just [returns an empty list](https://github.com/timoschick/pet/blob/60cec60272bdb6c3520de4cc4f3e33408eb018f9/pet/pvp.py#L281). When you define a [subclass of ``GenerativePVP``](https://github.com/timoschick/pet/blob/60cec60272bdb6c3520de4cc4f3e33408eb018f9/pet/pvp.py#L646) for your own task, you do not need to (and should not) specify any verbalizer at all.
